CREATE TABLE POST (
  ID INT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  CREATED_ON TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(32) NOT NULL,
  UPDATED_ON TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  UPDATED_BY VARCHAR(32) NOT NULL,
  VERSION INT
);